blob_storage_login:
    account_name: <account_name>
    account_key: <account_key>

sql_login:
    username: <username>
    password: <password>

telegram_creds:
    token: <local_dummy>
    chat_id: 0

s3_creds:
    access_key: <access_key
    secret_key: <secret_key>
    bucket_name: <bucket_name>
