paper_creds:
    api_key: <account_name>
    secret_key: <account_key>
    base_url: https://paper-api.alpaca.markets

live_creds:
    api_key: <account_name>
    secret_key: <account_key>
    base_url: https://{apiserver_domain}/v2/account
