#  Copyright (c) 2024, Boston Consulting Group.
#  Authors: Marco Scattolin
#  License: Proprietary

version: "3.4"
name: boilerplate
services:
  pg_db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${_POSTGRES_USER}
      POSTGRES_PASSWORD: ${_POSTGRES_PASSWORD}
      POSTGRES_DB: ${_POSTGRES_DB}
  basic_vm:
    build:
      context: ../
      dockerfile: docker/dockerfile_basic_vm
      args:
        PYTHON_VERSION: ${_PYTHON_VERSION}
    image: basic_vm
    environment:
      - PYTHONPATH=/opt
    ports:
      - 8888:8888
    volumes:
       - ../src:/opt/src
       - ../data:/opt/data
       - ../configs:/opt/configs
       - ../dags:/root/airflow/dags
       - ../notebooks:/opt/notebooks
    stdin_open: true
    tty: true
  airflow_vm:
    build:
      context: ../
      dockerfile: docker/dockerfile_airflow_vm
      args:
        PYTHON_VERSION: ${_PYTHON_VERSION}
        AIRFLOW_USERNAME: ${_AIRFLOW_USERNAME}
        AIRFLOW_EMAIL: ${_AIRFLOW_EMAIL}
        AIRFLOW_FIRSTNAME: ${_AIRFLOW_FIRSTNAME}
        AIRFLOW_LASTNAME: ${_AIRFLOW_LASTNAME}
        AIRFLOW_PASSWORD: ${_AIRFLOW_PASSWORD}
    image: airflow_vm
    environment:
      - PYTHONPATH=/opt
    ports:
      - 8888:8888
      - 8080:8080
    volumes:
       - ../src:/opt/src
       - ../data:/opt/data
       - ../configs:/opt/configs
       - ../dags:/root/airflow/dags
       - ../notebooks:/opt/notebooks
    command: sh -c "airflow scheduler -D & airflow webserver -D"
    stdin_open: true
    tty: true
  spark_vm:
    build:
      context: ../
      dockerfile: docker/dockerfile_spark_vm
      args:
        PYTHON_VERSION: ${_PYTHON_VERSION}
        SPARK_VERSION: ${_SPARK_VERSION}
        HADOOP_VERSION: ${_HADOOP_VERSION}
    image: spark_vm
    environment:
      - PYTHONPATH=/opt
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
       - ../src:/opt/src
       - ../data:/opt/data
       - ../configs:/opt/configs
       - ../dags:/root/airflow/dags
       - ../notebooks:/opt/notebooks
    stdin_open: true
    tty: true
